language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

before_script:
  - composer install
  - mysql -e 'CREATE DATABASE modera_security_bundle'
